import streamlit as st

# Page Config
st.set_page_config(
    page_title="PocketGuide 3.0",
    page_icon="🌍",
    layout="wide"
)

# Custom CSS for Design
st.markdown("""
    <style>
        body {
            background: linear-gradient(to bottom, #e0f7fa, #fff);
            font-family: 'Poppins', sans-serif;
            color: #2c3e50;
        }
        .title {
            font-size: 50px;
            font-weight: 700;
            color: #34495e;
            margin: 20px 0;
        }
        .subtitle {
            font-size: 20px;
            color: #7f8c8d;
            margin-bottom: 40px;
        }
        .button {
            background-color: #ff6f61;
            color: white;
            font-size: 18px;
            padding: 15px 30px;
            border-radius: 25px;
            border: none;
            margin: 10px auto;
            cursor: pointer;
            transition: transform 0.2s, background-color 0.2s;
        }
        .button:hover {
            background-color: #e74c3c;
            transform: scale(1.05);
        }
        .disclaimer {
            font-size: 14px;
            color: #95a5a6;
            text-align: center;
            margin-top: 60px;
        }
        .illustration {
            margin-top: 30px;
            text-align: center;
        }
        .illustration img {
            max-width: 80%;
            border-radius: 15px;
        }
    </style>
""", unsafe_allow_html=True)

# Title and Subtitle
st.markdown("<div class='title'>PocketGuide 3.0</div>", unsafe_allow_html=True)
st.markdown("<div class='subtitle'>Your elegant travel companion, powered by AI.</div>", unsafe_allow_html=True)

# Travel-themed Illustration
st.markdown("""
    <div class='illustration'>
        <img src='https://imgur.com/a/g0EbSr2' alt='Friendly Robot Tour Guide'>
    </div>
""", unsafe_allow_html=True)

# Sequential Buttons Logic
if "stage" not in st.session_state:
    st.session_state.stage = 0

if st.session_state.stage == 0:
    if st.button("Fetch Coordinates", key="button1"):
        st.session_state.stage = 1

elif st.session_state.stage == 1:
    if st.button("Translate Address", key="button2"):
        st.session_state.stage = 2

elif st.session_state.stage == 2:
    if st.button("Start Tour", key="button3"):
        st.session_state.stage = 3

if st.session_state.stage == 3:
    st.success("Enjoy your journey! 🚀")

# Disclaimer
st.markdown("<div class='disclaimer'>All information here is generated by an AI. Please verify all information to validate its truthfulness.</div>", unsafe_allow_html=True)
