import streamlit as st

# Set page configuration
st.set_page_config(
    page_title="PocketGuide 3.0",
    layout="centered"
)

# Apply custom CSS for clean, elegant styling
st.markdown(
    """
    <style>
        body {
            background-color: #f9f9f9;
            font-family: 'Arial', sans-serif;
        }
        .title {
            font-size: 36px;
            color: #2c3e50;
            font-weight: bold;
            margin-top: 20px;
        }
        .subtitle {
            font-size: 16px;
            color: #7f8c8d;
            margin-bottom: 30px;
        }
        .button {
            display: block;
            margin: 20px auto;
            width: 200px;
            height: 50px;
            font-size: 18px;
            font-weight: bold;
            color: #fff;
            background-color: #3498db;
            border: none;
            border-radius: 25px;
            cursor: pointer;
            transition: background-color 0.3s ease;
        }
        .button:hover {
            background-color: #2980b9;
        }
        .disclaimer {
            margin-top: 50px;
            font-size: 12px;
            color: #7f8c8d;
            text-align: center;
        }
    </style>
    """,
    unsafe_allow_html=True
)

# Title and Subtitle
st.markdown("<div class='title'>PocketGuide 3.0</div>", unsafe_allow_html=True)
st.markdown("<div class='subtitle'>Your AI-powered tour guide assistant</div>", unsafe_allow_html=True)

# Disclaimer
st.markdown(
    "<div class='disclaimer'>All information here is generated by an AI. Please verify all information to validate its truthfulness.</div>",
    unsafe_allow_html=True
)

# State for button clicks
if "stage" not in st.session_state:
    st.session_state.stage = 0

# Logic for button sequence
if st.session_state.stage == 0:
    if st.button("Fetch Coordinates", key="button1", help="Get the geographical coordinates for your location."):
        st.session_state.stage = 1

elif st.session_state.stage == 1:
    if st.button("Translate Address", key="button2", help="Translate an address into a preferred language."):
        st.session_state.stage = 2

elif st.session_state.stage == 2:
    if st.button("Start Tour", key="button3", help="Begin your AI-guided tour!"):
        st.session_state.stage = 3

# Optional final message or reset logic
if st.session_state.stage == 3:
    st.success("Enjoy your tour! Ready to explore?")
